---
- import_playbook: ../init/evaluate_groups.yml
  vars:
    # Do not allow adding hosts during upgrade.
    g_new_master_hosts: []
    g_new_node_hosts: []

- import_playbook: ../init/basic_facts.yml
- import_playbook: ../init/base_packages.yml
- import_playbook: ../init/cluster_facts.yml

- import_playbook: private/openshift_node_group.yml
