---

- name: restart docker
  systemd:
    name: container-engine
    state: restarted
  when: not docker_service_status_changed | default(false) | bool

- name: restart udev
  systemd:
    name: systemd-udevd
    state: restarted
    daemon_reload: yes
