---
# These tasks dispatch to the proper set of docker tasks based on the
# inventory:openshift_docker_use_system_container variable

- include: udev_workaround.yml
  when: docker_udev_workaround | default(False) | bool

- name: Use Package Docker if Requested
  include: package_docker.yml
  when: openshift.docker.use_system_container is not defined or openshift.docker.use_system_container == False

- name: Use System Container Docker if Requested
  include: systemcontainer_docker.yml
  when:
  - openshift.docker.use_system_container is defined
  - openshift.docker.use_system_container is True
