---
- name: update ca trust
  command: update-ca-trust
  notify:
    - restart docker after updating ca trust

- name: restart docker after updating ca trust
  systemd:
    name: container-engine
    state: restarted
  when: not openshift_certificates_redeploy | default(false) | bool
